# Install in /etc/nginx/conf.d/. These zones must be declared in nginx's http context.
limit_req_zone $binary_remote_addr zone=oknotika_admin_general:10m rate=60r/m;
limit_req_zone $binary_remote_addr zone=oknotika_admin_login:10m rate=5r/m;
